apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment  # Le nom du déploiement doit être correctement défini
  namespace: icgroup         # Vérifiez que le namespace est correct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4  # Utilisation de l'image officielle de pgAdmin 4
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@example.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
