apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: icgroup
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80         # Port exposé par le service (accessible par d'autres services ou via NodePort)
      targetPort: 80   # Port du conteneur PgAdmin
  type: NodePort       # Permet d'exposer le service à l'extérieur du cluster pour les tests (Minikube)
