apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  namespace: icgroup
  labels:
    app: odoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:13
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-pvc
